# This is the main pipelien which covers all the stages
# The tasks are stored in pipelines/steps.yml
# you can read more about this: 

stages:
  - stage: Dev
    displayName: 'Deploying to Development environment'
    jobs:
      - template: pipelines/steps.yml
        parameters:
          environment: Dev
          azureSubscription: 'PKM'
          WorkspaceName: pkm02 # Enter the Azure Sentinel Workspace name
          SubscriptionId: '6c6f34fb-ca67-408c-9fc5-98ee15fca9e8'
          ResourceGroupName: 'infra-management-p-rg'
          EnableSentinel: true
          analyticsRulesFile: SettingFiles/analytics-rules.json # leave empty if you dont want to configure Analytic rules
          huntingRulesFile: '' #SettingFiles/analytics-rules.json # leave empty if you dont want to configure Hunting rules
          PlaybooksFolder: Playbooks/ # leave empty if you dont want to configure Playbooks
          ConnectorsFile: '' #Connectors/connectors.json # leave empty if you dont want to configure Connectors
          WorkbooksFolder: '' #Workbooks/
          WorkbookSourceId: '' # leave empty if you dont want to configure Workbook

  - stage: Staging
    displayName: 'Deploying to Acceptance environment'
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/release'))
    jobs:
      - template: pipelines/steps.yml
        parameters:
          environment: Staging
          azureSubscription: ''
          WorkspaceName: '' # Enter the Azure Sentinel Workspace name
          SubscriptionId: '6c4444fb-ca67-4444-4444-98e4444ca9e8'
          ResourceGroupName: ''
          EnableSentinel: true
          analyticsRulesFile: SettingFiles/analytics-rules.json # leave empty if you dont want to configure Analytic rules
          huntingRulesFile: '' #SettingFiles/analytics-rules.json # leave empty if you dont want to configure Hunting rules
          PlaybooksFolder: Playbooks/ # leave empty if you dont want to configure Playbooks
          ConnectorsFile: '' #Connectors/connectors.json # leave empty if you dont want to configure Connectors
          WorkbooksFolder: '' #Workbooks/
          WorkbookSourceId: '' # leave empty if you dont want to configure Workbook

  - stage: Production
    displayName: 'Deploying to Production environment'
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    jobs:
      - template: pipelines/steps.yml
        parameters:
          environment: Production
          azureSubscription: ''
          WorkspaceName: ''  # Enter the Azure Sentinel Workspace name
          SubscriptionId: '6c4444fb-ca67-4444-4444-98e4444ca9e8'
          ResourceGroupName: ''
          EnableSentinel: true
          analyticsRulesFile: SettingFiles/analytics-rules.json # leave empty if you dont want to configure Analytic rules
          huntingRulesFile: '' #SettingFiles/analytics-rules.json # leave empty if you dont want to configure Hunting rules
          PlaybooksFolder: Playbooks/ # leave empty if you dont want to configure Playbooks
          ConnectorsFile: '' #Connectors/connectors.json # leave empty if you dont want to configure Connectors
          WorkbooksFolder: '' #Workbooks/
          WorkbookSourceId: '' # leave empty if you dont want to configure Workbook
